export const actionTypes = {
  CREATE_NEW_POST: 'CREATE_NEW_POST',
  POST_ERROR: 'POST_ERROR',
  CLEAR_ERROR: 'CLEAR_ERRORS',
  POST_LOADING: 'POST_LOADING',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
  FETCH_PAGINATED_POSTS: 'FETCH_PAGINATED_POSTS',
  SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE',
  FETCH_ALL_MYPOSTS: 'FETCH_ALL_MYPOSTS',
  EDIT_POST: 'EDIT_POST',
  DELETE_POST: 'DELETE_POST'
}