export const actionTypes = {
  CREATE_NEW_POST: 'CREATE_NEW_POST',
  POST_ERROR: 'POST_ERROR',
  CLEAR_ERROR: 'CLEAR_ERRORS',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
  FETCH_PAGINATED_POSTS: 'FETCH_PAGINATED_POSTS',
  SET_ACTIVE_PAGE: 'SET_ACTIVE_PAGE'
}