export const actionTypes = {
  GET_ERRORS: 'GET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  USER_LOADING: 'USER_LOADING',
  USER_LOADED: 'USER_LOADED',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  REGISTER_USER: 'REGISTER_USER'
}